// import { Component, OnInit } from '@angular/core';
// import { PengajuanPinjamanService } from '../pengajuan-pinjaman.service';
// import { FormDetailResponse, FormPengajuanPinjaman } from '../pengajuan-pinjaman';
// import { ActivatedRoute } from '@angular/router';

// @Component({
//   selector: 'app-detail',
//   templateUrl: './detail-pengajuan-pinjaman.component.html',
//   styleUrl: './detail-pengajuan-pinjaman.component.css'
// })
// export class DetailPengajuanPinjamanComponent {
//   form?: FormDetailResponse;

//   constructor(private router: ActivatedRoute, private pengajuanPinjamanService: PengajuanPinjamanService) { }

//   async ngOnInit() {
//     this.refreshFormDetail();
//   }

//   async refreshFormDetail() {
//     const id: number = this.router.snapshot.params['id'];
//     try{
//       this.pengajuanPinjamanService.getDetailPengajuanPinjaman(id).subscribe({
//         next: (data) => {
//           this.form = data;
//           console.log(this.form);
//         },
//       })
//     } catch (error) {
//       console.error('Error fetching data:', error)
//     }
//   }
//   acceptPengajuan(id: number) {
//     this.pengajuanPinjamanService.getDetailPengajuanPinjaman(id).subscribe({
//       next: (currentData) => {
//         const updatedData = {
//           ...currentData,
//           statusPengajuan: "Diterima"
//         };
//         this.pengajuanPinjamanService.updateStatusPengajuanPinjaman(id, updatedData).subscribe({
//           next: (response) => {
//             console.log("Status updated successfully", response);
//             // Handle successful update here
//           },
//           error: (error) => {
//             console.error("Error updating status:", error);
//             // Handle error here
//           }
//         });
//       },
//       error: (error) => {
//         console.error("Error fetching current data:", error);
//         // Handle error here
//       }
//     });
//   }
//   rejectPengajuan(id: number) {
//     this.pengajuanPinjamanService.getDetailPengajuanPinjaman(id).subscribe({
//       next: (currentData) => {
//         const updatedData = {
//           ...currentData,
//           statusPengajuan: "Ditolak"
//         };
//         this.pengajuanPinjamanService.updateStatusPengajuanPinjaman(id, updatedData).subscribe({
//           next: (response) => {
//             console.log("Status updated successfully", response);
//             // Handle successful update here
//           },
//           error: (error) => {
//             console.error("Error updating status:", error);
//             // Handle error here
//           }
//         });
//       },
//       error: (error) => {
//         console.error("Error fetching current data:", error);
//         // Handle error here
//       }
//     });
//   }
// }

import { Component, ElementRef, ViewChild, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { PengajuanPinjamanService } from '../pengajuan-pinjaman.service';
import { FormDetailResponse } from '../pengajuan-pinjaman';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Component({
  selector: 'app-detail',
  templateUrl: './detail-pengajuan-pinjaman.component.html',
  styleUrls: ['./detail-pengajuan-pinjaman.component.css'],
})
export class DetailPengajuanPinjamanComponent implements OnInit {
  form?: FormDetailResponse;
  showSLIKTable: boolean = false;
  slikGenerated: boolean = false;
  slikData: any[] = [];

  @ViewChild('slikTable') slikTable!: ElementRef;

  constructor(
    private router: ActivatedRoute,
    private pengajuanPinjamanService: PengajuanPinjamanService
  ) { }

  ngOnInit() {
    this.refreshFormDetail();
  }

  refreshFormDetail() {
    const id: number = +this.router.snapshot.params['id']; // Unary plus to convert string to number
    this.pengajuanPinjamanService.getDetailPengajuanPinjaman(id).subscribe({
      next: (data) => {
        this.form = data;
        console.log(this.form);
      },
      error: (error) => console.error('Error fetching data:', error)
    });
  }

  createMinimalPinjaman() {
    if (!this.form) {
      console.error("Form data is not loaded.");
      return;
    }
    const id: number = +this.router.snapshot.params['id'];

    const minimalPinjamanData = {
      idPinjaman: null, // This will likely be auto-generated by your backend.
      pinjamanToUser: {
          idUser: this.form.formToUser.idUser,
          nameUser: this.form.formToUser.nameUser,
          nikUser: this.form.formToUser.nikUser,
      },
      pinjamanToAdmin: {
        idAdmin: 1,
        nameAdmin: "Admin Name",
        nppAdmin: "Admin NPP",
        usernameAdmin: "admin",
        passwordAdmin: "123456",
        profilepictAdmin: null,
      },
      alamat_pinjaman: this.form.alamatKtp,
      sisa_tagihan_pinjaman: 100000000,
      status_pinjaman: "lancar",
      tanggal_bayar_tagihan_pinjaman: new Date().toISOString(),
      tanggal_realisasi_pinjaman: new Date().toISOString(),
      total_bayar_tagihan_pinjaman: 400000000,
      

      amounts_bunga_berjalan_pinjaman: null,
      amounts_sisa_pokok_pinjaman: null,
      deskripsi_pembayaran_pinjaman: null,
      kolektabilitas_pinjaman: null,
      payoffs_bunga_berjalan_pinjaman: null,
      payoffs_sisa_pokok_pinjaman: null,
      rebates_bunga_berjalan_pinjaman: null,
      rebates_sisa_pokok_pinjaman: null,
      status_tagihan_pinjaman: null,
      total_amounts_pinjaman: null,
      total_payoffs_pinjaman: null,
      total_rebates_pinjaman: null,
    };
  
    this.pengajuanPinjamanService.createPinjamanMinimal(minimalPinjamanData).subscribe({
      next: (response) => {
        console.log("Minimal Pinjaman created successfully", response);
        
        // Update status of pengajuan to "Diterima"
        const updatedData = {
          ...this.form,
          statusPengajuan: "Diterima"
        };
        this.pengajuanPinjamanService.updateStatusPengajuanPinjaman(id, updatedData).subscribe({
          next: (response) => {
            console.log("Status updated successfully", response);
            this.refreshFormDetail();
          },
          error: (error) => {
            console.error("Error updating status:", error);
          }
        });
      },
      error: (error) => console.error("Error creating minimal Pinjaman:", error)
    });
    
  }

  
  createPengajuanPinjaman(data: any) {
    this.pengajuanPinjamanService.createPengajuanPinjaman(data).subscribe({
      next: (response) => console.log("New pengajuan pinjaman created successfully", response),
      error: (error) => console.error("Error creating new pengajuan pinjaman:", error)
    });
  }
  rejectPengajuan(id: number) {
    this.pengajuanPinjamanService.getDetailPengajuanPinjaman(id).subscribe({
      next: (currentData) => {
        const updatedData = {
          ...currentData,
          statusPengajuan: "Ditolak"
        };
        this.pengajuanPinjamanService.updateStatusPengajuanPinjaman(id, updatedData).subscribe({
          next: (response) => {
            console.log("Status updated successfully", response);
            // Handle successful update here
          },
          error: (error) => {
            console.error("Error updating status:", error);
            // Handle error here
          }
        });
      },
      error: (error) => {
        console.error("Error fetching current data:", error);
        // Handle error here
      }
    });
  }
  generateSLIK(): void {
    if (!this.slikGenerated) {
      const slikData = [
        {
          fasilitas: 'Plafon Efektif',
          kredit: '2.263.328,00',
          lc: '0,00',
          fasilitasLain: '0,00',
          total: '2.263.328,00',
          kualitas: '1 / Januari 2020'
        },
        {
          fasilitas: 'Baki Debet',
          kredit: '2.263.328,00',
          lc: '0,00',
          fasilitasLain: '0,00',
          total: '2.263.328,00',
          kualitas: '1 / Januari 2020'
        }
      ];
  
      this.slikData = slikData; // Assign slikData to slikData property

      this.showSLIKTable = true; // Show the SLIK table
       // Create PDF
   
    }
    //   this.slikGenerated = true; // Set slikGenerated to true to indicate that the table has been generated
    // } else {
    //   console.log("SLIK sudah digenerate sebelumnya.");
    // }
  }
  downloadSLIK(){
    //pdf generate table to pdf
    var doc = new jsPDF()
    autoTable(doc, {html:"#slik-debitur",
    theme: 'grid',
  })
    doc.save("SLIK-Debitur")
  }
}
